This is an example of how to do classification on a simple data in TensorFlow. Basically we are building a simple model helping a frined to choose a house to buy.


In [61]:
%matplotlib inline
%config IPCompleter.greedy=True
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [62]:
# load the house data CSV file.
dataframe=pd.read_csv('data.csv')
print(dataframe.head())
print ()
print(dataframe.describe())

# remove the columns we don't care
dataframe=dataframe.drop(['price','sq_price'],axis=1)

# only use 10 rows of the dataset
dataframe=dataframe[:10]
print()
print(dataframe)

   index    area  bathrooms     price    sq_price
0      0  2104.0        3.0  399900.0  190.066540
1      1  1600.0        3.0  329900.0  206.187500
2      2  2400.0        3.0  369000.0  153.750000
3      3  1416.0        2.0  232000.0  163.841808
4      4  3000.0        4.0  539900.0  179.966667

           index         area  bathrooms          price    sq_price
count  47.000000    47.000000  47.000000      47.000000   47.000000
mean   23.000000  2000.680851   3.170213  340412.659574  175.259506
std    13.711309   794.702354   0.760982  125039.899586   37.929278
min     0.000000   852.000000   1.000000  169900.000000  113.727721
25%    11.500000  1432.000000   3.000000  249900.000000  151.258519
50%    23.000000  1888.000000   3.000000  299900.000000  169.900000
75%    34.500000  2269.000000   4.000000  384450.000000  196.616621
max    46.000000  4478.000000   5.000000  699900.000000  318.587106

   index    area  bathrooms
0      0  2104.0        3.0
1      1  1600.0        3.0
2 

In [63]:
# introduce the labels
dataframe['y1']=[1,1,1,0,0,1,0,1,1,1]
dataframe['y2']=dataframe['y1']==0
dataframe['y2']=dataframe['y2'].astype(int)
dataframe


index    area  bathrooms  y1  y2
0      0  2104.0        3.0   1   0
1      1  1600.0        3.0   1   0
2      2  2400.0        3.0   1   0
3      3  1416.0        2.0   0   1
4      4  3000.0        4.0   0   1
5      5  1985.0        4.0   1   0
6      6  1534.0        3.0   0   1
7      7  1427.0        3.0   1   0
8      8  1380.0        3.0   1   0
9      9  1494.0        3.0   1   0

In [64]:
# shape the data into matrices to feed it to TensorFlow
inputX=dataframe.loc[:,['area','bathrooms']].as_matrix()
inputY=dataframe.loc[:,['y1','y2']].as_matrix()
print(inputX)
print(inputY)


[[  2.10400000e+03   3.00000000e+00]
 [  1.60000000e+03   3.00000000e+00]
 [  2.40000000e+03   3.00000000e+00]
 [  1.41600000e+03   2.00000000e+00]
 [  3.00000000e+03   4.00000000e+00]
 [  1.98500000e+03   4.00000000e+00]
 [  1.53400000e+03   3.00000000e+00]
 [  1.42700000e+03   3.00000000e+00]
 [  1.38000000e+03   3.00000000e+00]
 [  1.49400000e+03   3.00000000e+00]]
[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]


In [65]:
# Set the paramters for the training process
learning_rate=0.000001
training_epochs=2000
display_step=50
n_samples=inputY.size

In [66]:
# Define the TensorFlow operations
x=tf.placeholder(tf.float32,[None,2])
W=tf.Variable(tf.zeros([2,2]))
b=tf.Variable(tf.zeros([2]))

y_values=tf.add(tf.matmul(x,W),b)
# Use softmax as an 'activation functuon'
y=tf.nn.softmax(y_values)

y_=tf.placeholder(tf.float32,[None,2])

In [67]:
# Cost function: Mean Square Erroe
cost=tf.reduce_sum(tf.pow(y_-y,2))/(2*n_samples)
# Set up optimizer
optimizer=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [70]:
# Initialize variables ans tensorflow session
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

In [72]:
# Train the model
for i in range(training_epochs):
    sess.run(optimizer,feed_dict={x:inputX,y_:inputY})
    
    # display logs per epoch step
    if (i)%display_step==0:
        cc=sess.run(cost,feed_dict={x:inputX,y_:inputY})
        print('Training steps:','%04d' %(i),'cost=','{:.9f}'.format(cc))

print('Optimization finished!')
training_cost=sess.run(cost,feed_dict={x:inputX,y_:inputY})
print('Training cost=',training_cost,'W=',sess.run(W),'b=',sess.run(b),'\n')


Training steps: 0000 cost= 0.114958666
Training steps: 0050 cost= 0.109539941
Training steps: 0100 cost= 0.109539866
Training steps: 0150 cost= 0.109539807
Training steps: 0200 cost= 0.109539732
Training steps: 0250 cost= 0.109539673
Training steps: 0300 cost= 0.109539606
Training steps: 0350 cost= 0.109539531
Training steps: 0400 cost= 0.109539464
Training steps: 0450 cost= 0.109539405
Training steps: 0500 cost= 0.109539315
Training steps: 0550 cost= 0.109539248
Training steps: 0600 cost= 0.109539196
Training steps: 0650 cost= 0.109539129
Training steps: 0700 cost= 0.109539054
Training steps: 0750 cost= 0.109538987
Training steps: 0800 cost= 0.109538913
Training steps: 0850 cost= 0.109538853
Training steps: 0900 cost= 0.109538779
Training steps: 0950 cost= 0.109538712
Training steps: 1000 cost= 0.109538652
Training steps: 1050 cost= 0.109538577
Training steps: 1100 cost= 0.109538510
Training steps: 1150 cost= 0.109538436
Training steps: 1200 cost= 0.109538361
Training steps: 1250 cost

In [73]:
# Predict to see if our friend will like the house 
sess.run(y,feed_dict={x:inputX})


array([[ 0.71125221,  0.28874779],
       [ 0.66498977,  0.33501023],
       [ 0.73657656,  0.26342347],
       [ 0.64718789,  0.35281211],
       [ 0.78335613,  0.2166439 ],
       [ 0.70069474,  0.29930523],
       [ 0.65866327,  0.34133676],
       [ 0.64828628,  0.35171372],
       [ 0.64368278,  0.35631716],
       [ 0.65480113,  0.3451989 ]], dtype=float32)

It seems all of 10 houses are worth to buy. That makes it get 7/10 correct. Not a terrible impressive. A model with a hidden layer should do better.